- pgx/_dwg/backgammon.py
- pgx/_dwg/hex.py
- pgx/_dwg/othello.py
- pgx/_visualizer.py
> [Visualizer] Enhance Visualizer

- pgx/_bridge_bidding.py
- tests/test_bridge_bidding.py
観測をDeepMindの特徴量で返すobserveを実装する #705
> [BridgeBidding] Add observe

- pgx/_chess_utils.py
- pgx/chess.py
> [Chess] Speed up `_legal_action_mask` by caching piece positions

- pgx/_dwg/bridge_bidding.py
#723
actと数字の対応を直した。playerに関してはそのままでいいはず。
> [BridgeBidding] Fix `_make_bridge_dwg` in visualizer 

- pgx/chess.py
- tests/test_chess.py
> [Chess] Implement `observe`

- fig/generate_chess_svg_animation.py
- fig/generate_go_gif.py
- pgx/__init__.py
- pgx/_visualizer.py
- pgx/core.py
From #739
The animation isn't quite smooth and it generates huge files (the board is copied to each frame) but it works!
TODO
@sotetsuk Do you like the API?
> SVG animation

- .github/workflows/ci.yml
- .github/workflows/fmt.yml
resolve #749 
Not quite sure but I hope this works
> [CI] Make CI work on forked repos

- pgx/_visualizer.py
- pgx/go.py
> [Visualizer] FIx slow loading

- .readthedocs.yaml
> [Docs] Unuse reathedocs

- pgx/bridge_bidding.py
- tests/test_bridge_bidding.py
- workspace/bridge_bidding-duplicate.py
#714 
現在の実装でduplicate可能か検証し、試しに実装してみる
> [BridgeBidding] Test and implement the duplicate bridge API

- pgx/_test.py
- pgx/core.py
- tests/test_seaquest.py
> Revert "[Experimental] add `state._info` to `State`"

- pgx/tic_tac_toe.py
- tests/test_tic_tac_toe.py
Use image-like feature like other zero-sum two-player envs.
> [TicTacToe] Change observation dims

- setup.py
> [Docs] Add long description to README

- pgx/minatar/asterix.py
- pgx/minatar/breakout.py
- pgx/minatar/freeway.py
- pgx/minatar/seaquest.py
- pgx/minatar/space_invaders.py
- tests/test_asterix.py
- tests/test_breakout.py
- tests/test_freeway.py
- tests/test_seaquest.py
- tests/test_space_invaders.py
> [MinAtar] Add tests for reward/termination

- pgx/minatar/asterix.py
- pgx/minatar/breakout.py
- pgx/minatar/freeway.py
- pgx/minatar/seaquest.py
- pgx/minatar/space_invaders.py
> [MinAtar] Remove unused termination condition

- README.md
> Revert "[Docs] Fix table width in README"

- pgx/minatar/breakout.py
> [Breakout] fix id

- pgx/_gardner_chess.py
- pgx/v1.py
> [Gardner Chess] FEN conversion

- pgx/_mahjong/_hand.py
- pgx/_mahjong/_shanten.py
- pgx/_mahjong/_yaku.py
- tests/test_mahjong.py
- workspace/mahjong_benchmark/benchmark.py
> [Mahjong] Faster jit compile time

- pgx/backgammon.py
- tests/test_backgammon.py
> [Backgammon] use `_rng_key`

- pgx/bridge_bidding.py
- workspace/test_bridge_openspiel.py
#888 openspielを用い、Bridgeの`observation`, `rewards`をtestする
> [BridgeBidding] Add test with openspiel

- pgx/__init__.py
- pyproject.toml
- setup.py
> [API] Add `pgx.__version__`

- pgx/_src/dwg/backgammon.py
- pgx/_src/visualizer.py
> [Backgammon, Visualizer] Add dice to SVG 

- pgx/_src/visualizer.py
- pgx/minatar/asterix.py
- pgx/minatar/breakout.py
- pgx/minatar/freeway.py
- pgx/minatar/seaquest.py
- pgx/minatar/space_invaders.py
```py
import jax
import pgx
env = pgx.make("minatar-asterix")
state = jax.jit(jax.vmap(env.init))(jax.random.split(jax.random.PRNGKey(0), 4))
pgx.save_svg(state, "asterix.svg")  # ok
state.save_svg("asterix.svg")  # ok
state.to_svg()  # ok
state # ok
pgx.save_svg_animation([state], "asterix.svg")  # assertion
```
> [MinAtar] Fix visualization

- pgx/_src/dwg/backgammon.py
> [Backgammon] Fix background visualization

- docs/bridge_bidding.md
> [Docs] Fix bridge fig

- pgx/_mahjong/_mahjong2.py
- pgx/_src/dwg/mahjong.py
- tests/test_mahjong.py
> [Mahjong] Convert to `json` format

- pgx/_mahjong/_mahjong2.py
- pgx/_mahjong/_yaku.py
- tests/test_mahjong.py
> [Mahjong] Dora-score calculation

- examples/alphazero/README.md
- examples/alphazero/train.py
https://api.wandb.ai/links/sotetsuk/979hmps8
> [Example] Extract loss input computation

- pgx/_src/dwg/go.py
- pgx/_src/visualizer.py
- pgx/go.py
- tests/test_go.py
#1127 
Add new `GameState` class and move all go-specific attributes inside of `GameState`.
Suppose there is behavior change.
> [Go] Separate go specific attributes

- pgx/_src/games/go.py
- pgx/go.py
> [Go] Add new logic class

- pgx/tic_tac_toe.py
- tests/test_tic_tac_toe.py
> [TicTacToe] Split game specific methods

- pgx/connect_four.py
> [ConnectFour] Separate game specific methods

- pgx/_src/dwg/connect_four.py
- pgx/_src/games/connect_four.py
- pgx/connect_four.py
- tests/test_connect_four.py
> [ConnectFour] Extract `games/connect_four.py`

- pgx/_src/dwg/go.py
- pgx/_src/games/go.py
- tests/test_go.py
lines: 356 -> 242
The behavior is supposed to be unchanged. The performance is also tie.
test: https://colab.research.google.com/drive/1DSqt2FuuEoYdS4eYA0YglTZGBO8-tcyK?usp=sharing
> [Go] internal refactor

- pgx/_src/dwg/chess.py
- pgx/chess.py
- pgx/experimental/chess.py
- tests/test_chess.py
> [Chess] Separate Chess specific attributes

- pgx/_src/dwg/chess.py
- pgx/chess.py
- pgx/experimental/chess.py
- tests/test_chess.py
> [Chess] Extract game logic functions

- pgx/_src/games/chess.py
- pgx/chess.py
- pgx/experimental/chess.py
> [Chess] Add game class

- pgx/_src/visualizer.py
> [Visualization] Remove file name assertion

- pgx/_src/games/chess.py
> [Chess] speed up `_is_attacked`

- pgx/_src/dwg/shogi.py
- pgx/_src/shogi_utils.py
- pgx/shogi.py
- tests/test_shogi.py
> [Shogi] Extract game specific attributes

- pgx/_src/games/shogi.py
- pgx/shogi.py
> [Shogi] Add `Game` class

- docs/hex.md
Did you mean `player_id` instead of `player_ix`?
> [Docs] Update hex.md

- pgx/_src/dwg/hex.py
- pgx/_src/games/hex.py
- pgx/_src/visualizer.py
- pgx/hex.py
> [Hex] Create `Game` class

- pgx/othello.py
- tests/test_othello.py
> [Othello] Extract game specific attributes

- .github/workflows/ci.yml
> [CI] Remove `py3.13` CI (hotfix)
