sotetsuk/pgx

- pgx/bridge_bidding.py
test_apiで生じていたint32をint8にキャストしてしまっているwarningをなくす。
player_id, player_positonを格納する値以外のintをint32に統一した。
> [BridgeBidding] Fix test_api warning

- pgx/_visualizer.py
#728 
`pgx._visualizer`において、`states.dealer`を入れるようにした。
dealerがNに固定されてしまうバグを修正。
> [BridgeBidding] Fix part of state passed in `pgx._make_bridge_dwg` is not updated

- pgx/bridge_bidding.py
#730 
`state.shuffled_players`にて、player_id:0,1のチームとplayer_id:2, 3のチームがNS, EWに固定されていたバグを取り除いた。
> [BridgeBidding] Fix shuffled_players

- pgx/bridge_bidding.py
- tests/test_bridge_bidding.py
#714 
`BridgeBidding(core.Env)`にillegal_actionに対するpenaltyとして-7600(ブリッジの最低score)を与えるようにした。
> [BridgeBidding] Add illegal action penalty

- workspace/bridge_bidding-duplicate.py
`vmap`と`duplicate`の実行順序を変更し、ロスを無くした自然なduplicate対戦を実装する
#714
> [BridgeBidding] Change the executing order of `vmap` and `duplicate`

- pgx/_flax/struct.py
Hotfix. From https://github.com/google/flax/commit/d129b664519465c238d333b446de472817073380
#743 #779
> [Internal] Support old jax version in dataclass

- Makefile
- pgx/_flax/struct.py
- pgx/_mahjong/_action.py
- pgx/animal_shogi.py
- pgx/backgammon.py
- pgx/bridge_bidding.py
- pgx/chess.py
- pgx/connect_four.py
- pgx/core.py
- pgx/go.py
- pgx/hex.py
- pgx/kuhn_poker.py
- pgx/leduc_holdem.py
- pgx/minatar/asterix.py
- pgx/minatar/breakout.py
- pgx/minatar/freeway.py
- pgx/minatar/seaquest.py
- pgx/minatar/space_invaders.py
- pgx/othello.py
- pgx/play2048.py
- pgx/shogi.py
- pgx/sparrow_mahjong.py
- pgx/tic_tac_toe.py
- setup.py
- workspace/how_to_develop/README.md
Reverts sotetsuk/pgx#787
#743
I found that #787 changes raise errors at least in two environments:
- Colab TPU
- M1 Mac
I will revert it and we will use the copied flax dataclass. It's very stable.
> Revert "[API] Use chex's dataclass instead of flax's dataclass"

- pgx/animal_shogi.py
- pgx/backgammon.py
- pgx/bridge_bidding.py
- pgx/chess.py
- pgx/connect_four.py
- pgx/go.py
- pgx/hex.py
- pgx/kuhn_poker.py
- pgx/leduc_holdem.py
- pgx/minatar/asterix.py
- pgx/minatar/breakout.py
- pgx/minatar/freeway.py
- pgx/minatar/seaquest.py
- pgx/minatar/space_invaders.py
- pgx/othello.py
- pgx/play2048.py
- pgx/shogi.py
- pgx/sparrow_mahjong.py
- pgx/tic_tac_toe.py
- pgx/v1.py
I misunderstood that no Pgx environment require the truncation but actually MinAtar suits may continue forever.
So we remove `auto_reset` implementation, which replace the last state.
This `auto_reset` is not appropriate when the truncation happens (as bootstrap is impossible)
> [API] Revert `auto_reset` argument

- pgx/leduc_holdem.py
- tests/test_leduc_holdem.py
fix #925 
```py
import jax
import jax.numpy as jnp
import pgx
env = pgx.make("leduc_holdem")
init_fn = jax.jit(env.init)
step_fn = jax.jit(env.step)
CALL = jnp.int32(0)
RAISE = jnp.int32(1)
FOLD = jnp.int32(2)
key = jax.random.PRNGKey(1)
state = init_fn(key)
state = step_fn(state, RAISE)
assert not state.terminated
state = step_fn(state, FOLD)
assert state.terminated  # OK
```
> [Leduc Holdem] Fix a bug when folding in the first round

- pgx/chess.py
- tests/test_chess.py
kingside and queenside castling
> [Chess] Fix `_possible_piece_positions` when castling

- pgx/backgammon.py
- tests/test_backgammon.py
The number of dimension of `legal_action_mask` should be `src * 6 = 156` but it was `src * 6 + 6 = 162`
- Fixed the dimension num of `legal_action_mask` and passed the test.
- Translated some remaining Japanese comments into English.
> [Backgammon] Fix the number of legal_action_mask dimension.

- pgx/play2048.py
- tests/test_play2048.py
This state transition returns `-92` as reward due to overflow.
This PR changes `int8` to `int32` and update version to `v1`.
> [2048] Fix reward overflow

- pgx/backgammon.py
I added some comments to clarify the contents of the feature `playable_dice_count_vec`.
Together with #1046 , it will solve the issue on the understandability of the feature.
> [Backgammon] Add description to the playable_dice_count_vec

- pgx/_src/api_test.py
- pgx/_src/chess_utils.py
- pgx/_src/gardner_chess_utils.py
- pgx/_src/shogi_utils.py
- pgx/animal_shogi.py
- pgx/backgammon.py
- pgx/bridge_bidding.py
- pgx/chess.py
- pgx/connect_four.py
- pgx/experimental/bridge_bidding.py
- pgx/gardner_chess.py
- pgx/go.py
- pgx/hex.py
- pgx/kuhn_poker.py
- pgx/leduc_holdem.py
- pgx/othello.py
- pgx/play2048.py
- pgx/shogi.py
- pgx/sparrow_mahjong.py
- pgx/tic_tac_toe.py
- tests/test_backgammon.py
- tests/test_bridge_bidding.py
- tests/test_go.py
- tests/test_hex.py
- tests/test_othello.py
- tests/test_play2048.py
- tests/test_sparrow_mahjong.py
- tests/test_tic_tac_toe.py
Found some buggy behaviors in `int8` (e.g., failed to indexing via `int8` var)
> [API] Use `int32` instead of `int8/16`

- pgx/_src/struct.py
> [dataclass] Fix dataclass mutable defaults error

- examples/alphazero/README.md
- examples/alphazero/train.py
https://api.wandb.ai/links/sotetsuk/8w0or84k
> [Example] Use optax policy loss

- pgx/mahjong/_env.py
cf. https://github.com/sotetsuk/pgx/issues/1070
> [Mahjong] Reduce compilation/run time of `_pass()`

- pgx/go.py
> [Go] Extract game logic functions

- pgx/_src/games/go.py
> [Go] Use `NamedTuple` instead of `dataclass`

- pgx/_src/dwg/tictactoe.py
- pgx/_src/games/tic_tac_toe.py
- pgx/tic_tac_toe.py
- tests/test_tic_tac_toe.py
> [TicTacToe] Extract `games/tic_tac_toe.py`

- pgx/_src/api_test.py
- pgx/_src/games/go.py
- pgx/_src/visualizer.py
- pgx/go.py
Currently, this raises error:
```python
@jax.jit
def f():
return Game(size=9).init().size
print(f())
```
> [Go] Fix `size` attribute jittable

- pgx/_src/chess_utils.py
- pgx/_src/gardner_chess_utils.py
Importing `_src/chess_utils.py` currently takes between 10 and 15 seconds.
It is mainly due to the fact that all pre-computations are made on `jax.numpy` array, which are really slow.
This PR reduces the import time to ~1s, by using `numpy` array instead, and converting them to `jax.numpy` array at the end.
> [Chess] Accelerate `chess_utils.py` import (jnp => np)

- pgx/bridge_bidding.py
Add additional 10M train dataset:
```
dds_results/train_025.npy 
...
dds_results/train_124.npy
```
Move dataset to HuggingFace
> [Bridge] Enhance DDS dataset

- examples/alphazero/train.py
The use of `jax.tree_map` triggers the following warning. 
```
DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
```
Therefore `jax.tree_map` is replaced by `jax.tree_util.tree_map` which is available in any JAX version.
> Replace deprecated jax.tree_map function with jax.tree_util.tree_map

- pgx/_src/dwg/animalshogi.py
- pgx/animal_shogi.py
The pieces are defined in the following P→**B**→**R** order in pgx/animal_shogi.py.
```python
PAWN = jnp.int32(0)
BISHOP = jnp.int32(1)
ROOK = jnp.int32(2)
KING = jnp.int32(3)
GOLD = jnp.int32(4)
```
However the visualizer shows the numbers of pieces in hands with the following P→**R**→**B** order.
```python
for i, piece_num, piece_type in zip(range(6), state._hand.flatten(), ["P", "R", "B", "P", "R", "B"]):
```
This difference incurs the following bug of showing incorrect hand state.
In the following states, black king captures white **bishop**, but the number of **rook** in black hand is increased.
In the following states, black player drops **bishop**, but the number of **rook** in black hand is decreased.
I propose to use consistent P→B→R order.
> [Animal Shogi] Modify the visualizer of animal shogi.

- pgx/animal_shogi.py
- tests/test_animal_shogi.py
The current implementation of animal_shogi.py checks the reach of GOLD with following expression.
```
is_neighbour & ((dx != 0) | (dy != +1))
```
This means the following reach.
```
***
*G*
* *
```
However, the correct reach of GOLD is the following.
```
***
*G*
* 
```
Therefore, I propose to modify the expression as follows.
```
is_neighbour & ((dx == 0) | (dy != +1))
```
I found this bug because of the following move of white gold, which led to mate.
> [Animal Shogi] Modify the move of GOLD in animal_shogi.py

- pgx/animal_shogi.py
- tests/test_animal_shogi.py
In animal shogi, dropping PAWN on the final rank is legal.
> standard restrictions on where one may drop a Chick, such as not being allowed to give immediate checkmate, have two Chicks on a file, or drop the Chick on the final rank, do not apply. [^1]
However, the current implementation forbids dropping PAWN on final rank.
Make dropping PAWN on the final rank legal.
I also added a simple test to ‎`test_buggy_samples`‎ in test_animal_shogi.py.
An interesting fact is reported that dropping PAWN on final rank is sometimes the only winning move.
> there are positions in which “dropping a hiyoko piece on the promote zone” is the only winning move. [^2]
[^1]: [Dōbutsu shōgi (English Wikipedia)](https://en.wikipedia.org/wiki/D%C5%8Dbutsu_sh%C5%8Dgi#:~:text=standard%20restrictions%20on%20where%20o …
> [Animal Shogi] Dropping PAWN on the final rank is legal.

- .github/workflows/ci.yml
- README.md
Now JAX support only 3.10+ (from 0.4.31)
> [CI] Drop py3.8 and test py3.9

- pgx/_src/games/go.py
This PR includes the superko logic change.
> [Go] Use hash

- pgx/_src/games/chess.py
| `_legal_action_mask` | 4220 | 944.2ms |
| `_flip` | 92 | 27.0ms |
| `_is_checked` | 206 | 56.2ms |
| `_is_pseudo_legal` | 136 | 58.2ms |
| `_hash_castling_en_passant` | 37 | 17.6ms |
| `_apply_move` | 331 | 92.6ms |
| `_update_history` | 57 | 27.3ms |
> [Chess] Skip `_flip` in checking mate

- pgx/_src/games/chess.py
c.f. #1230 
| `_legal_action_mask` | 2467 | 728.2ms |
| `_flip` | 92 | 33.4ms |
| `_is_checked` | 206 | 68.8ms |
| `_is_pseudo_legal` | 136 | 40.4ms |
| `_hash_castling_en_passant` | 37 | 18.5ms |
| `_apply_move` | 331 | 107.0ms |
| `_update_history` | 57 | 30.9ms |
> [Chess] Reduce `_is_checked` call

- pgx/_src/games/chess.py
#1231 
| `_legal_action_mask` | 1689 | 468.3ms |
| `_flip` | 92 | 38.0ms |
| `_is_checked` | 206 | 59.3ms |
| `_is_pseudo_legal` | 136 | 39.2ms |
| `_hash_castling_en_passant` | 37 | 18.6ms |
| `_apply_move` | 331 | 98.8ms |
| `_update_history` | 57 | 30.5ms |
> [Chess] Summarize `_is_checked` calls

- pgx/_src/games/chess.py
- pgx/_src/games/chess_utils.py
#1232 #1233
| `_legal_action_mask` | 1674 | 427.0ms |
| `_flip` | 92 | 28.4ms |
| `_is_checked` | 203 | 52.8ms |
| `_is_pseudo_legal` | 134 | 35.8ms |
| `_hash_castling_en_passant` | 37 | 17.6ms |
| `_apply_move` | 331 | 92.8ms |
| `_update_history` | 57 | 27.5ms |
> [Chess] Enhance `CAN_MOVE`

- pgx/_src/games/chess.py
- pgx/_src/games/chess_utils.py
- pgx/experimental/chess.py
#1232
| `_legal_action_mask` | 1652 | 514.8ms |
| `_flip` | 91 | 26.2ms |
| `_is_checked` | 206 | 56.0ms |
| `_is_pseudo_legal` | 136 | 37.6ms |
| `_hash_castling_en_passant` | 37 | 17.4ms |
| `_apply_move` | 258 | 68.4ms |
| `_update_history` | 57 | 24.6ms |
> [Chess] Remove cached info

- pgx/_src/games/chess.py
| `_legal_action_mask` | 1631 | 485.1ms |
| `_flip` | 91 | 25.2ms |
| `_is_checked` | 203 | 53.4ms |
| `_is_pseudo_legal` | 134 | 35.0ms |
| `_hash_castling_en_passant` | 37 | 17.4ms |
| `_apply_move` | 258 | 69.3ms |
| `_update_history` | 57 | 28.6ms |
> [Chess] Simplify `legal_underpromotions`

- pgx/_src/games/chess.py
- pgx/_src/games/chess_utils.py
#1236 
Also removed unused pawn move destinations from cache #1174
| `_legal_action_mask` | 1499 | 465.2ms |
| `_flip` | 91 | 26.2ms |
| `_is_checked` | 156 | 50.2ms |
| `_hash_castling_en_passant` | 37 | 21.3ms |
| `_apply_move` | 258 | 74.5ms |
| `_update_history` | 57 | 29.0ms |
> [Chess] Remove `_is_pseudo_legal`

- pgx/_src/visualizer.py
We cannot visualize the initial state of `hex`.
It raises `TypeError: 'int' object is not subscriptable`.
This is caused by the following code in line 396 of visualizer.py.
```
self.config["BOARD_WIDTH"] = four_dig(
_state._size[0] * 1.5  # type:ignore
)
```
The current implementation above tries to read `_state._size`, which is int object.
Also, python raises `TypeError`, therefore it would not be caught by the exception handler `except IndexError:`.
I propose to convert `_state._size` into `int` via one dimensional `jnp.array`.
I think this is stabler because both `int` and `jaxlib.xla_extension.ArrayImpl` with one element can be converted to `int`.
If we run the following code, we get `TypeError: 'int' object is not subscriptable`.
```
import jax
import pgx
print(pgx.__version__)   # …
```
> [Hex] Modify visualizer.py to handle TypeError when displaying the initial state of hex.

- pgx/_src/games/chess.py
As `is_attacked` call is bottleneck, this PR intends to reduce it.
In normal play, the number of legal action is < 200. See these extreme examples without black pieces:
| | 9 Queens | 8 Queens |
|:---:|:---:|:---:|
| # legal actions | `206` | `196` |
| board | <img width="356" alt="image" src="https://github.com/user-attachments/assets/ec768c6e-63b9-46e2-8b07-f323f9ecf805"> | <img width="339" alt="image" src="https://github.com/user-attachments/assets/1b7ba5a1-9b89-4b11-9e9e-a6f421c49fe6"> |
These examples are found by black box optimization. There might be larger example but I believe 200 is quite enough.
> [Chess] Reduce `_is_attacked` call

- examples/alphazero/train.py
Fix typo: `my_model_parmas` → `my_model_params`.
> [AlphaZero] Fix minor typo in train.py

- pgx/_src/dwg/hex.py
- pgx/_src/visualizer.py
- pgx/hex.py
- tests/test_hex.py
> [Hex] Extract game specific attributes

- pgx/_src/dwg/hex.py
- pgx/hex.py
> [Hex] Extract logic functions

- pgx/_src/games/hex.py
#1127
Use last action information.
> [Hex] Enhance terminal computation

- pgx/_src/games/hex.py
- pgx/hex.py
> [Hex] Use `_player_order` 

- pgx/shogi.py
Thank you for developing your nice library. I am really enjoying using it.
In Shogi environment, `current_player` is not randomly initialized.
This can cause issues when the users use the information of `current_player` in their code.
The following code can reproduce this issue.
```python
import pgx
import jax
env = pgx.make("chess")
chess_states = jax.vmap(env.init)(jax.random.split(jax.random.key(0), 16))
print(chess_states.current_player) # -> [0 0 1 1 1 0 1 1 1 0 1 0 0 0 1 0]
env = pgx.make("shogi")
shogi_states = jax.vmap(env.init)(jax.random.split(jax.random.key(0), 16))
print(shogi_states.current_player) # -> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
```
In the `_init` function of [pgx/pgx/shogi.py](https://github.com/sotetsuk/pgx/blob/main/pgx/shogi.py#L52-L55), the variable …
> [Shogi] Randomly initialize the `current_player` variable.
